# 1. Unique identifier for your project
sonar.projectKey=onemolecastle_startbootstrap-agency

# 2. Your SonarCloud organization name (usually your GitHub username)
sonar.organization=onemolecastle

# 3. Where the code is (the current folder)
sonar.sources=.

# 4. Tell SonarCloud what kind of project this is
sonar.projectNamespace=public
sonar.javascript.node.max_old_space_size=4096

# 5. Production Best Practice: Exclude third-party library files
# We don't want to be blamed for bugs in Bootstrap's own code!
sonar.exclusions=assets/vendor/**, js/scripts.js
