name: static and dynamic code build
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: check out code from github to runner
        uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '18.x'
      - name: install dependecies and build
        run: |
          npm install
          npm run build
      - name: deploy to staging
        run: |
          cp -r $GITHUB_WORKSPACE/dist/ /var/www/html/
          echo "deploy successful"
          # fixed typo
  
