name: static and dynamic code build
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: check out code from github to runner
        uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '18.x'
      - name: install dependecies and build
        run: |
          npm install
          npm run build
      - name: deploy to staging
        run: |
          npm install pm2 -g
          pm2 start scripts/start.js
          pm2 logs
  
